### ISSUE TITLE
isService() fstat throws exception on Windows

### ISSUE THREAD

**Issue by binki** [fbbdev/node-fastcgi#17]
It seems that the `isService()` method throws an exception on Windows when not run under FastCGI instead of returning `false` like it should:

```
$ node index.cgi
fs.js:977
  return binding.fstat(fd);
                 ^

Error: EISDIR: illegal operation on a directory, fstat
    at Error (native)
    at Object.fs.fstatSync (fs.js:977:18)
    at Object.exports.isService (C:\Users\ohnob\repos\yet-another-multiplayer-fps-game\node_modules\node-fastcgi\index.js:54:15)
    at module.exports (C:\Users\ohnob\repos\yet-another-multiplayer-fps-game\node_modules\autoserve\index.js:10:14)
    at module.exports (C:\Users\ohnob\repos\yet-another-multiplayer-fps-game\node_modules\express-autoserve\index.js:10:5)
    at Object.<anonymous> (C:\Users\ohnob\repos\yet-another-multiplayer-fps-game\index.cgi:5:29)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
```

```
$ node --version
v6.4.0
```

```
$ uname -a
MSYS_NT-10.0 DESKTOP-A4G2C0J 2.6.0(0.304/5/3) 2016-09-07 20:45 x86_64 Msys
```

**Comment by fbbdev** [comment]
I knew this day would come. :smile:

Windows is quite a different beast when it comes to FastCGI. I'm working on a solution, I'll keep you updated.

**Comment by binki** [comment]
Just for clarification, I wasn’t actually trying to set up FastCGI on Windows, but just trying to get the `isService()` fallback working. Though support for whatever Windows calls FastCGI would be cool too, at least having the `isService()` check not explode would be most useful to me ;-).

Thanks!

**Comment by fbbdev** [comment]
Yeah, I guessed that, but I can't just lie to windows users. They already
have Microsoft lying to them! :P

**Comment by fbbdev** [comment]
I ended up lying and added a warning in the README :disappointed:. To handle the problem correctly I'd have to add a dependency on a c++ extension and I don't want to.
